"""
Bweave Account Management

This module provides the BweaveAccount class for loading keystores
and signing transaction hashes with secp256k1 ECDSA.
"""

from typing import Optional
import json
from pathlib import Path
from eth_account import Account
from eth_keys import keys
from .crypto import sign
from .exceptions import KeystoreError, SignatureError


class BweaveAccount:
    """
    Account for signing transactions using Web3 keystores or raw private keys

    Supports:
    - Loading from Ethereum Web3 v3 keystore JSON files
    - Loading from raw 32-byte private keys
    - Signing 32-byte transaction hashes
    - Deriving Ethereum addresses

    Example:
        >>> # From keystore
        >>> account = BweaveAccount.from_keystore("wallet.json", "password")
        >>> account.address
        '0x1234...5678'

        >>> # From raw private key
        >>> account = BweaveAccount(b'\\x01' * 32)
        >>> r, s, v = account.sign_hash(keccak256(b"message"))
    """

    def __init__(self, private_key: bytes):
        """
        Initialize account from raw private key

        Args:
            private_key: 32-byte secp256k1 private key

        Raises:
            ValueError: If private_key not 32 bytes

        Example:
            >>> private_key = bytes.fromhex("1234...5678")
            >>> account = BweaveAccount(private_key)
        """
        if len(private_key) != 32:
            raise ValueError("Private key must be 32 bytes")

        self._private_key = private_key
        self._eth_key = keys.PrivateKey(private_key)
        self._address = self._eth_key.public_key.to_checksum_address()

    @classmethod
    def from_keystore(cls, keystore_path: str, password: str) -> 'BweaveAccount':
        """
        Load account from Ethereum Web3 v3 keystore file

        This method is compatible with keystores generated by the C++ wallet,
        as they both follow the Ethereum Web3 Keystore v3 standard.

        Args:
            keystore_path: Path to keystore JSON file
            password: Decryption password

        Returns:
            BweaveAccount instance

        Raises:
            KeystoreError: If file not found or decryption fails

        Example:
            >>> account = BweaveAccount.from_keystore("wallet.json", "mypass")
            >>> account.address
            '0x1234...5678'

        Note:
            The keystore must be Web3 v3 format with:
            - AES-128-CTR encryption
            - scrypt KDF (N=262144, r=8, p=1)
            - keccak256 MAC
        """
        path = Path(keystore_path)
        if not path.exists():
            raise KeystoreError(f"Keystore not found: {keystore_path}")

        try:
            with open(path, 'r') as f:
                keystore = json.load(f)

            # Decrypt using eth_account (compatible with C++ wallet)
            private_key = Account.decrypt(keystore, password)

            return cls(private_key)

        except FileNotFoundError:
            raise KeystoreError(f"Keystore file not found: {keystore_path}")
        except json.JSONDecodeError as e:
            raise KeystoreError(f"Invalid JSON in keystore: {e}")
        except ValueError as e:
            # eth_account raises ValueError for wrong password
            raise KeystoreError(f"Decryption failed (wrong password?): {e}")
        except Exception as e:
            raise KeystoreError(f"Failed to load keystore: {e}")

    @classmethod
    def from_private_key_hex(cls, private_key_hex: str) -> 'BweaveAccount':
        """
        Load account from hex-encoded private key

        Args:
            private_key_hex: 64-character hex string (with or without 0x prefix)

        Returns:
            BweaveAccount instance

        Raises:
            ValueError: If hex string is invalid or wrong length

        Example:
            >>> account = BweaveAccount.from_private_key_hex("0x1234...")
            >>> account2 = BweaveAccount.from_private_key_hex("1234...")
        """
        if private_key_hex.startswith('0x'):
            private_key_hex = private_key_hex[2:]

        if len(private_key_hex) != 64:
            raise ValueError(f"Private key hex must be 64 characters, got {len(private_key_hex)}")

        try:
            private_key = bytes.fromhex(private_key_hex)
        except ValueError as e:
            raise ValueError(f"Invalid hex string: {e}")

        return cls(private_key)

    def sign_hash(self, signing_hash: bytes) -> tuple[bytes, bytes, int]:
        """
        Sign 32-byte transaction hash

        Args:
            signing_hash: 32-byte hash from transaction.generate_signing_hash()

        Returns:
            (r, s, v) signature tuple where:
            - r: 32 bytes
            - s: 32 bytes
            - v: int (recovery id, 0 or 1)

        Raises:
            ValueError: If signing_hash not 32 bytes
            SignatureError: If signing fails

        Example:
            >>> from .crypto import keccak256
            >>> from .encoding import rlp_encode_transaction
            >>> tx_data = [0, 1, b'\\x12'*20, 0, b'data', 1000]
            >>> signing_hash = keccak256(rlp_encode_transaction(tx_data))
            >>> r, s, v = account.sign_hash(signing_hash)
            >>> len(r), len(s), v in (0, 1)
            (32, 32, True)
        """
        if len(signing_hash) != 32:
            raise ValueError(f"signing_hash must be 32 bytes, got {len(signing_hash)}")

        try:
            return sign(self._private_key, signing_hash)
        except Exception as e:
            raise SignatureError(f"Signing failed: {e}")

    @property
    def address(self) -> str:
        """
        Get Ethereum address (checksummed, with 0x prefix)

        Returns:
            Checksummed Ethereum address string

        Example:
            >>> account.address
            '0x1234567890123456789012345678901234567890'
        """
        return self._address

    @property
    def address_bytes(self) -> bytes:
        """
        Get address as 20-byte binary (for transaction 'from' field)

        Returns:
            20-byte address

        Example:
            >>> len(account.address_bytes)
            20
        """
        return bytes.fromhex(self._address[2:])  # Remove 0x prefix

    @property
    def public_key(self) -> bytes:
        """
        Get 64-byte uncompressed public key (no 0x04 prefix)

        Returns:
            64-byte public key

        Example:
            >>> len(account.public_key)
            64
        """
        return self._eth_key.public_key.to_bytes()
