# Base image
FROM ubuntu:24.04

# Prevent interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install build tools and dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    clang \
    llvm \
    lldb \
    lld \
    libboost-dev \
    libssl-dev \
    openssl \
    net-tools \
    openssh-server \
    python3-requests \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set working directory inside container
WORKDIR /app

# Copy your project folder into the container
COPY ../.. /app

# Optional: build at image build time
# RUN mkdir build && cd build && cmake .. && make

# Default command
CMD ["bash"]

