# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on Ubuntu + Windows (Clang + MSVC)

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "Build type"
        default: "Debug"
        type: string
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      ASAN_OPTIONS: detect_leaks=1:abort_on_error=1:malloc_context_size=10:log_path=/tmp/asan/asan.log:strict_string_checks=1
      UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1
      LSAN_OPTIONS: verbosity=2
      CTEST_OUTPUT_ON_FAILURE: 1
      # This will be set at runtime (see step below), but default it here
      # ASAN_SYMBOLIZER_PATH: /usr/bin/llvm-symbolizer      
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu with Clang
          - os: ubuntu-latest
            label: x86_64
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Debug

          # Windows with MSVC
          # - os: windows-latest
          #   label: x86_64
          #   c_compiler: cl
          #   cpp_compiler: cl
          #   build_type: Debug

          # macOS ARM64 with Clang
          # - os: macos-latest
          #   label: arm64
          #   c_compiler: clang
          #   cpp_compiler: clang++
          #   build_type: Debug

          # macOS x64 with Clang
          # - os: macos-15
          #   label: x86_64
          #   c_compiler: clang
          #   cpp_compiler: clang++
          #   build_type: Debug

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
          
    #######################################################
    # Install dependencies
    #######################################################
    # -------- Linux: Install Clang --------
    - name: Install Clang (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y openssh-server net-tools git cmake llvm clang lldb lld \
                            openssl libssl-dev libboost-dev libasan6 python3-pip python3-psutil
        # ensure asan log dir
        sudo mkdir -p /tmp/asan
        sudo chown $USER /tmp/asan
        python -m pip install --upgrade pip
        pip install -r test/functional/requirements.txt        

    # -------- Windows: Setup MSVC env --------
    - name: Setup MSVC (Windows only)
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1

    # Windows Boost (header-only)
    - name: Install Boost header-only (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        C:\Windows\System32\curl.exe -L -o boost.zip https://sourceforge.net/projects/boost/files/boost/1.85.0/boost_1_85_0.tar.bz2/download
        # Expand-Archive boost.zip -DestinationPath boost
        tar -xf boost.zip
        echo "Detected $env:NUMBER_OF_PROCESSORS cores"
        echo "BUILD_CORES=$env:NUMBER_OF_PROCESSORS" >> $env:GITHUB_ENV
        python -m pip install --upgrade pip
        python -m pip install -r test\functional\requirements.txt

    # macOS x64/ARM64: Install Clang + dependencies
    - name: Install Clang & dependencies (macOS x64/arm64)
      if: matrix.os == 'macos-latest' || matrix.os == 'macos-15'
      run: |
        brew update
        brew install llvm boost
        echo "LLVM path:"
        brew --prefix llvm
        echo "Using bundled Clang (Apple Clang)"
        python -m pip install --upgrade pip
        pip install -r test/functional/requirements.txt
        
      shell: bash

    #######################################################
    # Configure
    #######################################################      
    - name: Configure CMake (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cmake -B build \
          -DBUILD_TESTS=ON \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
      shell: bash
      
    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        cmake -B build `
          -DBUILD_TESTS=ON `
          -DBOOST_INCLUDEDIR=${{ github.workspace }}\boost_1_85_0       

    # macOS ARM64
    - name: Configure CMake (macOS)
      if: matrix.os == 'macos-latest' || matrix.os == 'macos-15'
      run: |
        cmake -B build \
          -DBUILD_TESTS=ON \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}

    #######################################################
    # Build
    #######################################################

    - name: Build (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "Building with cmake --build build -- -j$(nproc)"
        cmake --build build -- -j$(nproc)
      shell: bash

    - name: Build (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        echo Building with %BUILD_CORES% cores
        cmake --build build --config ${{ matrix.build_type }} -- /m:%BUILD_CORES%
      shell: cmd

    - name: Build (macOS)
      if: matrix.os == 'macos-latest' || matrix.os == 'macos-15'
      run: |
        sysctl -n hw.ncpu
        cmake --build build -- -j$(sysctl -n hw.ncpu)

    #######################################################
    # Unit Test
    #######################################################

    - name: Unit Test (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd build
        CTEST_OUTPUT_ON_FAILURE=1 ctest -V
      shell: bash
      # continue-on-error: true
      
    - name: Unit Test (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd build\src\test\Debug
        .\test_all.exe
      shell: pwsh
      continue-on-error: true

    - name: Unit Test (macOS)
      if: matrix.os == 'macos-latest' || matrix.os == 'macos-15'
      run: |
        cd build
        ctest -V
      continue-on-error: true

    #######################################################
    # Functional Test
    #######################################################

    - name: Functional Test (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd build
        test/functional/test_runner.py --tmpdir /tmp --nocleanup
      shell: bash
      # continue-on-error: true

    - name: Print ASAN logs (Linux)
      if: always() && matrix.os == 'ubuntu-latest'
      run: |
        echo "Checking for ASAN logs in /tmp/asan..."
        if ls /tmp/asan/*log* 1> /dev/null 2>&1; then
          echo "---- ASAN LOGS FOUND ----"
          ls -l /tmp/asan
          echo "---- PRINTING ASAN LOGS ----"
          cat /tmp/asan/*log* || true
          echo "---------------------------"
        else
          echo "No ASAN logs found."
        fi
    
    - name: Upload ASAN logs (Linux)
      if: always() && matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: asan-logs-${{ matrix.os }}
        path: /tmp/asan/*
        if-no-files-found: ignore

    - name: Functional Test (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd build
        python3 test\\functional\\test_runner.py --tmpdir "C:\Temp" --nocleanup
      shell: pwsh
      continue-on-error: true

    - name: Functional Test (macOS)
      if: matrix.os == 'macos-latest' || matrix.os == 'macos-15'
      run: |
        cd build
        test/functional/test_runner.py --tmpdir /tmp --nocleanup
      continue-on-error: true

    ############################################################
    # POST BUILD WITH DOCKER
    ############################################################
    - name: Run docker image (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd test/docker
        ./test.sh
      shell: bash
      continue-on-error: true

    - name: Upload logs artifact on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ matrix.os }}
        path: |
          /tmp/test_run_*
          /tmp/asan/*    
