# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on Ubuntu + Windows (Clang + MSVC)

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "Build type"
        default: "Debug"
        type: string
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu with Clang
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Debug

          # Windows with MSVC
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            build_type: Debug

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive    

    # -------- Linux: Install Clang --------
    - name: Install Clang (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y openssh-server net-tools git cmake llvm clang lldb lld openssl libssl-dev libboost-dev libasan6 python3-pip python3-psutil

    # -------- Windows: Setup MSVC env --------
    - name: Setup MSVC (Windows only)
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1

    # Windows Boost (header-only)
    - name: Install Boost header-only (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        C:\Windows\System32\curl.exe -L -o boost.zip https://sourceforge.net/projects/boost/files/boost/1.85.0/boost_1_85_0.tar.bz2/download
        # Expand-Archive boost.zip -DestinationPath boost
        tar -xf boost.zip
        echo "Detected $env:NUMBER_OF_PROCESSORS cores"
        echo "BUILD_CORES=$env:NUMBER_OF_PROCESSORS" >> $env:GITHUB_ENV
    
    - name: Configure CMake (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cmake -B build \
          -DBUILD_TESTS=ON \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
      shell: bash
      
    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        cmake -B build `
          -DBUILD_TESTS=ON `
          -DBOOST_INCLUDEDIR=${{ github.workspace }}\boost_1_85_0       

    - name: Build (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "Building with cmake --build build -- -j$(nproc)"
        cmake --build build -- -j$(nproc)
      shell: bash

    - name: Build (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        echo Building with %BUILD_CORES% cores
        cmake --build build --config ${{ matrix.build_type }} -- /m:%BUILD_CORES%
      shell: cmd

#    - name: Test
#      working-directory: build
#      run: ctest --output-on-failure --build-config ${{ matrix.build_type }}
#      shell: bash

    - name: Unit Test (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd build
        ctest -V
      shell: bash

    - name: Unit Test (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd build\\src\\test\\${{ matrix.build_type }}
        test_all.exe
      shell: bash
      
    - name: Functional Test (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd build
        test/functional/test_runner.py --tmpdir /tmp --nocleanup
      shell: bash

    - name: Functional Test (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd build
        python3 test\\functional\\test_runner.py --tmpdir "C:\Temp" --nocleanup
      shell: bash

    ############################################################
    # POST BUILD WITH DOCKER
    ############################################################
    - name: Run docker image (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd test/docker
        ./test.sh
      shell: bash
